### ISSUE TITLE
Import current Mailcow state

### ISSUE THREAD

**Issue by bilyboy785** [l-with/terraform-provider-mailcow#91]
I'm trying to migrate all my domains and mailboxes to terraform and search a way to import the current state. 
Is there any way to do this ?

**Comment by l-with** [comment]
Try following https://developer.hashicorp.com/terraform/language/import with the version 0.7.5 (I added import without test)

**Comment by bilyboy785** [comment]
Hi,

I try to import but doesn't work. After successfully import, when i plan ou try to apply : 

```
╷
│ Error: resourceAlias 'domain.com': danger (domain_exists, domain.com)
│ 
│   with module.mailcow_domaincom.mailcow_domain.customer_domain,
│   on ../../modules/cloudflare-mx-bldwebagency/main.tf line 6, in resource "mailcow_domain" "customer_domain":
│    6: resource "mailcow_domain" "customer_domain" {
```

**Comment by bilyboy785** [comment]
Hello,

Sorry for the delay.

In the bellow example from the doc : 

```
import {
  to = aws_instance.example
  id = "i-abcd1234"
}
resource "aws_instance" "example" {
  name = "hashi"
  # (other resource arguments...)
}
```

What should be the id for mailcow ? 

```
import {
  to = mailcow_domain.example
  id = "???"
}
resource "mailcow_domain" "example" {
  name = "example.com"
  # (other resource arguments...)
}
```

**Comment by l-with** [comment]
The id equal to the attribute domain.
